name: Test LaTeX generation

on:
  push:
  workflow_dispatch:

jobs:
  test-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5

    - name: Run script
      run: python utils.py
